version: '2'
services:
    financeiro-app:
        image: financeiro
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://financeiro-postgresql:5432/financeiro
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://financeiro-elasticsearch:9200
        ports:
            - 8080:8080
    financeiro-postgresql:
        extends:
            file: postgresql.yml
            service: financeiro-postgresql
    financeiro-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: financeiro-elasticsearch
