version: '2'
services:
    financeiro-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/financeiro/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=financeiro
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
